### ISSUE TITLE
[Test #1] Verify sound integration

### ISSUE THREAD

**Issue by lixf** [rohitban/18545-project#4]
Verify the integration of the sound module. 
The CPU side runs the sound routine: 
Code is [here](http://umlautllama.com/projects/pacdocs/mspac/mspac.asm).
Please read from 0x9d to 0xd2 and make sure it is doing what you expect!

**Comment by lixf** [comment]
Can we speed this one up please.

**Comment by rohitban** [comment]
Sounds are playing correctly. Interrupts need to be slowed down a bit.
