### ISSUE TITLE
[Test #4] Basic control

### ISSUE THREAD

**Issue by lixf** [rohitban/18545-project#7]
Can we control the sprites with a hardcoded value? 
- what's the left/right/up/down memory address??

**Comment by rohitban** [comment]
Timing on PDM sampler is working correctly

**Comment by lixf** [comment]
sw[1:0] is used for direction control in game. Tested for both 1-player and 2-player modes. 
sw[3:2] is used to set modes -- currently does not work.

**Comment by lixf** [comment]
Have a separate issue for voice control when we get there
